# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import oricli_rpc_pb2 as protos_dot_oricli__rpc__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/oricli_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModuleServiceStub(object):
    """The ModuleService represents a Python worker exposing one or more Brain Modules.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetManifest = channel.unary_unary(
                '/oricli.rpc.ModuleService/GetManifest',
                request_serializer=protos_dot_oricli__rpc__pb2.ManifestRequest.SerializeToString,
                response_deserializer=protos_dot_oricli__rpc__pb2.ManifestResponse.FromString,
                _registered_method=True)
        self.ExecuteOperation = channel.unary_unary(
                '/oricli.rpc.ModuleService/ExecuteOperation',
                request_serializer=protos_dot_oricli__rpc__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=protos_dot_oricli__rpc__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/oricli.rpc.ModuleService/HealthCheck',
                request_serializer=protos_dot_oricli__rpc__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=protos_dot_oricli__rpc__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ModuleServiceServicer(object):
    """The ModuleService represents a Python worker exposing one or more Brain Modules.
    """

    def GetManifest(self, request, context):
        """Discovery: The Go backbone asks the worker what modules and operations it supports.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteOperation(self, request, context):
        """Execution: The Go backbone tells the Python worker to run a specific module/operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health: Standard lightweight ping to ensure the Python worker hasn't hung.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManifest,
                    request_deserializer=protos_dot_oricli__rpc__pb2.ManifestRequest.FromString,
                    response_serializer=protos_dot_oricli__rpc__pb2.ManifestResponse.SerializeToString,
            ),
            'ExecuteOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteOperation,
                    request_deserializer=protos_dot_oricli__rpc__pb2.ExecuteRequest.FromString,
                    response_serializer=protos_dot_oricli__rpc__pb2.ExecuteResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=protos_dot_oricli__rpc__pb2.HealthCheckRequest.FromString,
                    response_serializer=protos_dot_oricli__rpc__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oricli.rpc.ModuleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oricli.rpc.ModuleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleService(object):
    """The ModuleService represents a Python worker exposing one or more Brain Modules.
    """

    @staticmethod
    def GetManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oricli.rpc.ModuleService/GetManifest',
            protos_dot_oricli__rpc__pb2.ManifestRequest.SerializeToString,
            protos_dot_oricli__rpc__pb2.ManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oricli.rpc.ModuleService/ExecuteOperation',
            protos_dot_oricli__rpc__pb2.ExecuteRequest.SerializeToString,
            protos_dot_oricli__rpc__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oricli.rpc.ModuleService/HealthCheck',
            protos_dot_oricli__rpc__pb2.HealthCheckRequest.SerializeToString,
            protos_dot_oricli__rpc__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
