# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/oricli_rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/oricli_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/oricli_rpc.proto\x12\noricli.rpc\"\x11\n\x0fManifestRequest\"X\n\x0eModuleMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x12\n\noperations\x18\x05 \x03(\t\"?\n\x10ManifestResponse\x12+\n\x07modules\x18\x01 \x03(\x0b\x32\x1a.oricli.rpc.ModuleMetadata\"^\n\x0e\x45xecuteRequest\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x13\n\x0bparams_json\x18\x03 \x01(\t\x12\x0f\n\x07task_id\x18\x04 \x01(\t\"N\n\x0f\x45xecuteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"<\n\x13HealthCheckResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t2\xf6\x01\n\rModuleService\x12H\n\x0bGetManifest\x12\x1b.oricli.rpc.ManifestRequest\x1a\x1c.oricli.rpc.ManifestResponse\x12K\n\x10\x45xecuteOperation\x12\x1a.oricli.rpc.ExecuteRequest\x1a\x1b.oricli.rpc.ExecuteResponse\x12N\n\x0bHealthCheck\x12\x1e.oricli.rpc.HealthCheckRequest\x1a\x1f.oricli.rpc.HealthCheckResponseB.Z,github.com/thynaptic/oricli-go/rpc;oriclirpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.oricli_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/thynaptic/oricli-go/rpc;oriclirpc'
  _globals['_MANIFESTREQUEST']._serialized_start=39
  _globals['_MANIFESTREQUEST']._serialized_end=56
  _globals['_MODULEMETADATA']._serialized_start=58
  _globals['_MODULEMETADATA']._serialized_end=146
  _globals['_MANIFESTRESPONSE']._serialized_start=148
  _globals['_MANIFESTRESPONSE']._serialized_end=211
  _globals['_EXECUTEREQUEST']._serialized_start=213
  _globals['_EXECUTEREQUEST']._serialized_end=307
  _globals['_EXECUTERESPONSE']._serialized_start=309
  _globals['_EXECUTERESPONSE']._serialized_end=387
  _globals['_HEALTHCHECKREQUEST']._serialized_start=389
  _globals['_HEALTHCHECKREQUEST']._serialized_end=409
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=411
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=471
  _globals['_MODULESERVICE']._serialized_start=474
  _globals['_MODULESERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
