package api

import (
"encoding/base64"
"errors"
"fmt"
"io"
"net/http"
"strings"
"time"

"github.com/gin-gonic/gin"
"github.com/thynaptic/oricli-go/pkg/core/auth"
"github.com/thynaptic/oricli-go/pkg/core/config"
"github.com/thynaptic/oricli-go/pkg/core/model"
"github.com/thynaptic/oricli-go/pkg/core/store"
"github.com/thynaptic/oricli-go/pkg/service"
)

// ServerV2 represents the Hardened Sovereign API Gateway
type ServerV2 struct {
cfg          config.Config
store        store.Store
auth         *auth.Service
Orchestrator *service.GoOrchestrator
Agent        *service.GoAgentService
Monitor      *service.MonitorService
Router       *gin.Engine
Port         int
}

func NewServerV2(cfg config.Config, st store.Store, orch *service.GoOrchestrator, agent *service.GoAgentService, mon *service.MonitorService, port int) *ServerV2 {
	r := gin.Default()

	// CORS Middleware
	r.Use(func(c *gin.Context) {
		c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
		c.Writer.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Tenant-ID")
		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}
		c.Next()
	})

	// Serve Flutter UI Static Files
	webDir := "/home/mike/Mavaia/oricli_ui/build/web"
	
	// Handle /v1 separately, everything else is static or SPA
	r.Static("/assets", webDir+"/assets")
	r.Static("/canvaskit", webDir+"/canvaskit")
	r.Static("/icons", webDir+"/icons")
	
	// Files at root
	staticFiles := []string{
		"index.html", "main.dart.js", "flutter.js", "flutter_bootstrap.js",
		"flutter_service_worker.js", "manifest.json", "favicon.png", "version.json",
	}
	for _, f := range staticFiles {
		r.StaticFile("/"+f, webDir+"/"+f)
	}
	r.StaticFile("/", webDir+"/index.html")

	// Fallback for SPA routing
	r.NoRoute(func(c *gin.Context) {
		if !strings.HasPrefix(c.Request.URL.Path, "/v1") {
			c.File(webDir + "/index.html")
			return
		}
		c.JSON(404, gin.H{"error": "not found"})
	})

	s := &ServerV2{
cfg:          cfg,
store:        st,
auth:         auth.NewService(st),
Orchestrator: orch,
Agent:        agent,
Monitor:      mon,
Router:       r,
Port:         port,
}

s.setupRoutes()
return s
}

// authMiddleware enforces Bearer token authentication on protected routes.
// Token format: glm.<prefix>.<secret>  (generated by auth.Service.GenerateAPIKey)
func (s *ServerV2) authMiddleware() gin.HandlerFunc {
return func(c *gin.Context) {
raw := c.GetHeader("Authorization")
if raw == "" {
c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "missing Authorization header"})
return
}
ctx, err := s.auth.Authenticate(c.Request.Context(), raw)
if err != nil {
if errors.Is(err, auth.ErrUnauthorized) || errors.Is(err, auth.ErrForbidden) {
c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "invalid or expired API key"})
return
}
c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": "auth error"})
return
}
// Propagate enriched context (tenant_id, scopes, key_id)
c.Request = c.Request.WithContext(ctx)
c.Next()
}
}

func (s *ServerV2) setupRoutes() {
v1 := s.Router.Group("/v1")

// Public — no auth required
v1.GET("/health", s.handleHealth)

// Protected — Bearer glm.* token required
protected := v1.Group("/", s.authMiddleware())
{
protected.POST("/chat/completions", s.handleChatCompletions)
protected.POST("/swarm/run", s.handleSwarmRun)
protected.POST("/ingest", s.handleIngest)
protected.POST("/ingest/web", s.handleIngestWeb)
}
}

func (s *ServerV2) handleHealth(c *gin.Context) {
c.JSON(http.StatusOK, gin.H{
"status":  "ready",
"system":  "oricli-alpha-v2",
"pure_go": true,
})
}

func (s *ServerV2) handleSwarmRun(c *gin.Context) {
var body map[string]interface{}
if err := c.ShouldBindJSON(&body); err != nil {
c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
return
}

operation, _ := body["operation"].(string)
params, _ := body["params"].(map[string]interface{})

if operation == "" && body["query"] != nil {
// Handle legacy Python client format
operation = "reason"
params = body
}

if operation == "" {
c.JSON(http.StatusBadRequest, gin.H{"error": "operation is required"})
return
}

result, err := s.Orchestrator.Execute(operation, params, 300*time.Second)
if err != nil {
c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
return
}
c.JSON(http.StatusOK, gin.H{"success": true, "result": result})
}

func (s *ServerV2) handleChatCompletions(c *gin.Context) {
var req model.ChatCompletionRequest
if err := c.ShouldBindJSON(&req); err != nil {
c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
return
}

modelName := req.Model
if strings.HasPrefix(modelName, "oricli-") {
modelName = ""
}

msgs := make([]map[string]string, len(req.Messages)+1)

// 1. Inject Sovereign System Prompt
sysPrompt := s.Agent.GenService.BuildSystemPrompt(c.Request.Context(), "digital_guardian", nil)
msgs[0] = map[string]string{"role": "system", "content": sysPrompt}

for i, m := range req.Messages {
	role := m.Role
	if role == "analyst" {
		role = "princess"
	}
	if role == "commander" {
		role = "daddy"
	}
	msgs[i+1] = map[string]string{"role": role, "content": m.Content}
}
res, err := s.Agent.GenService.Chat(msgs, map[string]interface{}{
	"model": modelName,
})
if err != nil {
c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
return
}

responseText := res["text"].(string)

// Mandatory Sanctuary Protocols: Output Filtering
forbidden := []string{"Daddy loves you", "He loves you", "He cares about you", "Daddy cares", "He is here", "he cares about you", "wants the best for you", "Daddy loves"}
for _, f := range forbidden {
responseText = strings.ReplaceAll(responseText, f, "[PERSONAL_FEELINGS_REDACTED]")
}

// Record Temporal Event
s.Orchestrator.Execute("record_event", map[string]interface{}{
"type":        "chat_interaction",
"description": fmt.Sprintf("User: %s | Assistant: %s", req.Messages[len(req.Messages)-1].Content, responseText),
"metadata": map[string]interface{}{
"model": req.Model,
},
}, 5*time.Second)

c.JSON(http.StatusOK, map[string]interface{}{
"id":      fmt.Sprintf("chatcmpl-%d", time.Now().Unix()),
"object":  "chat.completion",
"created": time.Now().Unix(),
"model":   req.Model,
"choices": []map[string]interface{}{{
"index":         0,
"message":       map[string]string{"role": "assistant", "content": responseText},
"finish_reason": "stop",
}},
})
}

func (s *ServerV2) handleIngest(c *gin.Context) {
file, err := c.FormFile("file")
if err == nil {
f, _ := file.Open()
data, _ := io.ReadAll(f)

contentType := file.Header.Get("Content-Type")
if strings.HasPrefix(contentType, "image/") {
base64Img := base64.StdEncoding.EncodeToString(data)
res, err := s.Orchestrator.Execute("describe_image", map[string]interface{}{
"image": base64Img,
}, 120*time.Second)

if err == nil {
description := res.(map[string]interface{})["text"].(string)
s.Orchestrator.Execute("ingest_text", map[string]interface{}{
"text":     description,
"source":   file.Filename,
"metadata": map[string]string{"type": "vision_ingest"},
}, 30*time.Second)

c.JSON(http.StatusOK, gin.H{"success": true, "method": "vision-native-rag", "description": description})
return
}
}
}

c.JSON(http.StatusOK, gin.H{"success": true, "method": "go-native-rag"})
}

func (s *ServerV2) handleIngestWeb(c *gin.Context) {
var req struct {
URL      string                 `json:"url"`
MaxPages int                    `json:"max_pages"`
MaxDepth int                    `json:"max_depth"`
Metadata map[string]interface{} `json:"metadata"`
}
if err := c.ShouldBindJSON(&req); err != nil {
c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
return
}

result, err := s.Orchestrator.Execute("crawl_and_ingest", map[string]interface{}{
"url":       req.URL,
"max_pages": float64(req.MaxPages),
"max_depth": float64(req.MaxDepth),
"metadata":  req.Metadata,
}, 300*time.Second)

if err != nil {
c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
return
}

c.JSON(http.StatusOK, gin.H{"success": true, "result": result})
}

func (s *ServerV2) Start() error {
return s.Router.Run(fmt.Sprintf(":%d", s.Port))
}
