package cognition

import (
	"fmt"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/thynaptic/oricli-go/pkg/memory"
	"github.com/thynaptic/oricli-go/pkg/state"
)

const (
	defaultReflectionLogPath = defaultReflectionAuditPath
	driftThreshold           = 0.40
	highDriftThreshold       = 0.25
)

type ReflectionStage string

const (
	StageChatGraph         ReflectionStage = "chat_graph"
	StageResearchPlan      ReflectionStage = "research_plan"
	StageResearchDiscover  ReflectionStage = "research_discovery"
	StageResearchSynthesis ReflectionStage = "research_synthesis"
	StageMAPlan            ReflectionStage = "multi_agent_plan"
	StageMAResearch        ReflectionStage = "multi_agent_research"
	StageMAVerify          ReflectionStage = "multi_agent_verify"
	StageMASynthesize      ReflectionStage = "multi_agent_synthesize"
)

type ReflectionOutcome string

const (
	ReflectionPass  ReflectionOutcome = "pass"
	ReflectionWarn  ReflectionOutcome = "warn"
	ReflectionSteer ReflectionOutcome = "steer"
	ReflectionVeto  ReflectionOutcome = "veto"
)

type ReflectionInput struct {
	Stage        ReflectionStage
	NodeID       string
	Step         int
	Goal         string
	Query        string
	Candidate    string
	SourceRefs   []string
	ContextFacts []string
	ShellFacts   []string
	Session      state.SessionState
	Metadata     map[string]string
}

type ReflectionDecision struct {
	Outcome         ReflectionOutcome
	RiskScore       float64
	RelevanceScore  float64
	Violations      []string
	NeedsCorrection bool
	CorrectionHint  string
	AuditID         string
	CacheHit        bool
}

// NodeOutputEvent is emitted by ThoughtGraph nodes for concurrent supervision.
type NodeOutputEvent struct {
	NodeID    string    `json:"node_id"`
	Step      int       `json:"step"`
	Input     string    `json:"input"`
	Output    string    `json:"output"`
	NextNode  string    `json:"next_node"`
	Timestamp time.Time `json:"timestamp"`
}

// SteerSignal indicates branch pruning + recovery routing.
type SteerSignal struct {
	NodeID    string    `json:"node_id"`
	Step      int       `json:"step"`
	Goal      string    `json:"goal"`
	Relevance float64   `json:"relevance"`
	Reason    string    `json:"reason"`
	Timestamp time.Time `json:"timestamp"`
}

type reflectionLogEntry struct {
	Timestamp     time.Time `json:"timestamp"`
	NodeID        string    `json:"node_id"`
	Step          int       `json:"step"`
	Goal          string    `json:"goal"`
	Relevance     float64   `json:"relevance"`
	Reason        string    `json:"reason"`
	OutputPreview string    `json:"output_preview"`
}

// ReflectionLayer monitors node outputs concurrently and emits steer signals on drift.
type ReflectionLayer struct {
	sm      *state.Manager
	mm      *memory.MemoryManager
	goal    string
	logPath string
	pred    *PredictiveForecaster

	inputCh chan NodeOutputEvent
	steerCh chan SteerSignal
	stopCh  chan struct{}
	wg      sync.WaitGroup
	mu      sync.RWMutex
}

// NewReflectionLayer creates a reflection layer bound to current session state.
func NewReflectionLayer(sm *state.Manager, goal string) *ReflectionLayer {
	return &ReflectionLayer{
		sm:      sm,
		goal:    strings.TrimSpace(goal),
		logPath: defaultReflectionLogPath,
		inputCh: make(chan NodeOutputEvent, 32),
		steerCh: make(chan SteerSignal, 8),
		stopCh:  make(chan struct{}),
	}
}

// SetLogPath overrides the reflection log path.
func (r *ReflectionLayer) SetLogPath(path string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if strings.TrimSpace(path) != "" {
		r.logPath = strings.TrimSpace(path)
	}
}

// AttachPredictive enables proactive forecasting during reflection.
func (r *ReflectionLayer) AttachPredictive(pred *PredictiveForecaster) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.pred = pred
}

// AttachMemory enables symbolic verification against live shell evidence in memory.
func (r *ReflectionLayer) AttachMemory(mm *memory.MemoryManager) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.mm = mm
}

// PredictiveNotices returns latest proactive interventions generated by reflection.
func (r *ReflectionLayer) PredictiveNotices() []string {
	r.mu.RLock()
	p := r.pred
	r.mu.RUnlock()
	if p == nil {
		return nil
	}
	return p.Notices()
}

// BindGoal updates monitoring goal at runtime.
func (r *ReflectionLayer) BindGoal(goal string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.goal = strings.TrimSpace(goal)
}

// Start starts concurrent supervision worker.
func (r *ReflectionLayer) Start() {
	if r == nil {
		return
	}
	r.wg.Add(1)
	go r.loop()
}

// Stop stops worker and drains.
func (r *ReflectionLayer) Stop() {
	if r == nil {
		return
	}
	close(r.stopCh)
	r.wg.Wait()
}

// Publish sends node output for concurrent reflection.
func (r *ReflectionLayer) Publish(ev NodeOutputEvent) {
	if r == nil {
		return
	}
	select {
	case r.inputCh <- ev:
	default:
		// Drop if overloaded; graph must keep moving.
	}
}

// WaitForSteer waits briefly for a steer signal.
func (r *ReflectionLayer) WaitForSteer(timeout time.Duration) (SteerSignal, bool) {
	if r == nil {
		return SteerSignal{}, false
	}
	if timeout <= 0 {
		select {
		case sig := <-r.steerCh:
			return sig, true
		default:
			return SteerSignal{}, false
		}
	}
	timer := time.NewTimer(timeout)
	defer timer.Stop()
	select {
	case sig := <-r.steerCh:
		return sig, true
	case <-timer.C:
		return SteerSignal{}, false
	}
}

func (r *ReflectionLayer) loop() {
	defer r.wg.Done()
	for {
		select {
		case <-r.stopCh:
			return
		case ev := <-r.inputCh:
			r.evaluateEvent(ev)
		}
	}
}

func (r *ReflectionLayer) evaluateEvent(ev NodeOutputEvent) {
	r.mu.RLock()
	pred := r.pred
	mm := r.mm
	r.mu.RUnlock()
	if pred != nil {
		pred.EvaluateAsync(ev.NodeID)
	}
	goal := r.currentGoal()
	if goal == "" || strings.TrimSpace(ev.Output) == "" {
		return
	}
	session := state.SessionState{}
	if r.sm != nil {
		session = r.sm.GetSnapshot()
	}
	shellFacts := CollectLiveShellFacts(mm, ev.Output, 10)
	policy := DefaultReflectionPolicy("balanced")
	decision, err := RunReflectionV2(ReflectionInput{
		Stage:      StageChatGraph,
		NodeID:     ev.NodeID,
		Step:       ev.Step,
		Goal:       goal,
		Query:      goal,
		Candidate:  ev.Output,
		Session:    session,
		ShellFacts: shellFacts,
		Metadata: map[string]string{
			"next_node": strings.TrimSpace(ev.NextNode),
		},
	}, policy)
	if err != nil || decision.Outcome == ReflectionPass {
		return
	}
	if policy.StatusEnabled {
		fmt.Printf("REFLECTION %s step=%d outcome=%s risk=%.2f\n", StageChatGraph, ev.Step, decision.Outcome, decision.RiskScore)
	}
	reason := strings.Join(decision.Violations, "; ")
	if strings.TrimSpace(reason) == "" {
		reason = "reflection intervention"
	}
	relevance := decision.RelevanceScore

	if decision.Outcome == ReflectionWarn {
		r.appendLog(reflectionLogEntry{
			Timestamp:     time.Now().UTC(),
			NodeID:        ev.NodeID,
			Step:          ev.Step,
			Goal:          goal,
			Relevance:     relevance,
			Reason:        reason,
			OutputPreview: truncate(strings.TrimSpace(ev.Output), 320),
		})
		return
	}

	sig := SteerSignal{NodeID: ev.NodeID, Step: ev.Step, Goal: goal, Relevance: relevance, Reason: reason, Timestamp: time.Now().UTC()}
	if r.sm != nil {
		delta := map[string]float64{
			"AnalyticalMode": 0.08,
			"Frustration":    0.05,
		}
		if decision.Outcome == ReflectionVeto || relevance < highDriftThreshold {
			delta["AnalyticalMode"] = 0.14
			delta["Frustration"] = 0.10
		}
		r.sm.UpdateDelta(delta)
		_ = r.sm.Save()
	}
	r.appendLog(reflectionLogEntry{
		Timestamp:     sig.Timestamp,
		NodeID:        ev.NodeID,
		Step:          ev.Step,
		Goal:          goal,
		Relevance:     relevance,
		Reason:        reason,
		OutputPreview: truncate(strings.TrimSpace(ev.Output), 320),
	})

	select {
	case r.steerCh <- sig:
	default:
		// If steering channel full, keep newest intent by replacing one.
		select {
		case <-r.steerCh:
		default:
		}
		select {
		case r.steerCh <- sig:
		default:
		}
	}
}

func (r *ReflectionLayer) currentGoal() string {
	r.mu.RLock()
	goal := r.goal
	r.mu.RUnlock()
	if strings.TrimSpace(goal) != "" {
		return strings.TrimSpace(goal)
	}
	if r.sm != nil {
		return strings.TrimSpace(r.sm.GetSnapshot().PrimaryGoal)
	}
	return ""
}

func (r *ReflectionLayer) appendLog(entry reflectionLogEntry) {
	r.mu.RLock()
	path := r.logPath
	r.mu.RUnlock()
	appendReflectionAudit(path, reflectionAuditEntry{
		Timestamp:       entry.Timestamp,
		Stage:           StageChatGraph,
		NodeID:          entry.NodeID,
		Step:            entry.Step,
		Outcome:         ReflectionSteer,
		RiskScore:       clamp01(1 - entry.Relevance),
		RelevanceScore:  entry.Relevance,
		Violations:      []string{entry.Reason},
		NeedsCorrection: false,
	})
}

var citationRefPattern = regexp.MustCompile(`\[[0-9]+\]`)

// RunReflectionV2 performs deterministic reflection checks and returns a stage-aware decision.
func RunReflectionV2(in ReflectionInput, policy ReflectionPolicy) (ReflectionDecision, error) {
	if !policy.Enabled {
		return ReflectionDecision{Outcome: ReflectionPass}, nil
	}
	key := reflectionCacheKey(in, policy)
	if cached, ok := globalReflectionCache.get(key); ok {
		cached.CacheHit = true
		return cached, nil
	}
	candidate := strings.TrimSpace(in.Candidate)
	if candidate == "" {
		return ReflectionDecision{}, fmt.Errorf("reflection candidate is empty")
	}
	goal := strings.TrimSpace(in.Goal)
	if goal == "" {
		goal = strings.TrimSpace(in.Query)
	}

	violations := make([]string, 0, 4)
	relevance := 1.0
	risk := 0.0
	if strings.TrimSpace(goal) != "" {
		relevance = relevanceScore(goal, candidate)
		if relevance < driftThreshold {
			driftRisk := clamp01((driftThreshold - relevance) / maxFloat(driftThreshold, 0.01))
			risk += driftRisk * 0.55
			if relevance < highDriftThreshold {
				violations = append(violations, "severe goal drift")
			} else {
				violations = append(violations, "goal drift")
			}
		}
	}

	contradictionPeak := 0.0
	for _, fact := range in.ContextFacts {
		score := DetectContradiction(candidate, fact)
		if score > contradictionPeak {
			contradictionPeak = score
		}
	}
	if contradictionPeak >= 0.72 {
		risk += clamp01(contradictionPeak) * 0.35
		violations = append(violations, fmt.Sprintf("contradiction risk %.2f", contradictionPeak))
	}

	symbolic := CheckSymbolicAssertions(candidate, in.Session, in.ShellFacts)
	if symbolic.Veto && len(symbolic.Violations) > 0 {
		risk += 0.70
		violations = append(violations, "symbolic veto: "+symbolic.Violations[0])
	}

	if policy.CitationGate && stageRequiresCitations(in.Stage) && len(in.SourceRefs) > 0 && !hasCitationMarker(candidate) {
		risk += 0.45
		violations = append(violations, "missing citation markers while sources are available")
	}
	risk = clamp01(risk)

	outcome := ReflectionPass
	switch {
	case risk >= policy.VetoThreshold:
		outcome = ReflectionVeto
	case risk >= policy.SteerThreshold:
		outcome = ReflectionSteer
	case risk >= policy.WarnThreshold:
		outcome = ReflectionWarn
	}
	if policy.EnforcementMode == "advisory" && (outcome == ReflectionSteer || outcome == ReflectionVeto) {
		outcome = ReflectionWarn
	}
	if policy.EnforcementMode == "hard" && outcome == ReflectionWarn {
		outcome = ReflectionSteer
	}
	decision := ReflectionDecision{
		Outcome:         outcome,
		RiskScore:       risk,
		RelevanceScore:  relevance,
		Violations:      uniqueReflectionStrings(violations),
		NeedsCorrection: outcome == ReflectionWarn || outcome == ReflectionSteer || outcome == ReflectionVeto,
		CorrectionHint:  "realign to goal, remove contradictions, preserve concise factual output",
		AuditID:         reflectionAuditID(in.Stage, in.Step, in.NodeID),
	}
	appendReflectionAudit(policy.AuditLogPath, reflectionAuditEntry{
		Timestamp:       time.Now().UTC(),
		Stage:           in.Stage,
		NodeID:          strings.TrimSpace(in.NodeID),
		Step:            in.Step,
		Outcome:         decision.Outcome,
		RiskScore:       decision.RiskScore,
		RelevanceScore:  decision.RelevanceScore,
		Violations:      decision.Violations,
		NeedsCorrection: decision.NeedsCorrection,
		AuditID:         decision.AuditID,
	})
	globalReflectionCache.set(key, decision)
	return decision, nil
}

func stageRequiresCitations(stage ReflectionStage) bool {
	switch stage {
	case StageResearchSynthesis, StageMAResearch, StageMAVerify, StageMASynthesize:
		return true
	default:
		return false
	}
}

func hasCitationMarker(s string) bool {
	return citationRefPattern.MatchString(strings.TrimSpace(s))
}

func maxFloat(a, b float64) float64 {
	if a > b {
		return a
	}
	return b
}

func uniqueReflectionStrings(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, v := range in {
		v = strings.TrimSpace(v)
		if v == "" || seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	return out
}

func relevanceScore(goal, output string) float64 {
	g := tokenizeReflection(goal)
	o := tokenizeReflection(output)
	if len(g) == 0 || len(o) == 0 {
		return 0.0
	}

	goalSet := make(map[string]bool, len(g))
	for _, t := range g {
		goalSet[t] = true
	}
	shared := 0
	for _, t := range o {
		if goalSet[t] {
			shared++
		}
	}
	ratio := float64(shared) / float64(len(goalSet))
	if strings.Contains(strings.ToLower(output), strings.ToLower(goal)) {
		ratio += 0.25
	}
	if ratio > 1 {
		ratio = 1
	}
	return ratio
}

func tokenizeReflection(s string) []string {
	s = strings.ToLower(strings.TrimSpace(s))
	repl := strings.NewReplacer(",", " ", ".", " ", ";", " ", ":", " ", "(", " ", ")", " ", "[", " ", "]", " ", "{", " ", "}", " ", "/", " ", "\\", " ")
	s = repl.Replace(s)
	stop := map[string]bool{
		"the": true, "and": true, "for": true, "with": true, "that": true, "this": true,
		"from": true, "your": true, "into": true, "have": true, "been": true, "about": true,
	}
	seen := make(map[string]bool)
	var out []string
	for _, t := range strings.Fields(s) {
		if len(t) < 3 || stop[t] || seen[t] {
			continue
		}
		seen[t] = true
		out = append(out, t)
	}
	return out
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	if n < 4 {
		return s[:n]
	}
	return s[:n-3] + "..."
}
