// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/oricli_rpc.proto

package oriclirpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_protos_oricli_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_oricli_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_protos_oricli_rpc_proto_rawDescGZIP(), []int{0}
}

type ModuleMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Operations    []string               `protobuf:"bytes,5,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleMetadata) Reset() {
	*x = ModuleMetadata{}
	mi := &file_protos_oricli_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleMetadata) ProtoMessage() {}

func (x *ModuleMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_protos_oricli_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleMetadata.ProtoReflect.Descriptor instead.
func (*ModuleMetadata) Descriptor() ([]byte, []int) {
	return file_protos_oricli_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleMetadata) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*ModuleMetadata      `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_protos_oricli_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_oricli_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_protos_oricli_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ManifestResponse) GetModules() []*ModuleMetadata {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ExecuteRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ModuleName string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Operation  string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// JSON serialized parameters to keep the schema flexible across 250+ modules
	ParamsJson string `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	// Tracing/Context info passed from Go
	TaskId        string `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_protos_oricli_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_oricli_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_protos_oricli_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ExecuteRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ExecuteRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *ExecuteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// JSON serialized result payload
	ResultJson string `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// Error message if success == false
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_protos_oricli_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_oricli_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_protos_oricli_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_protos_oricli_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_oricli_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_protos_oricli_rpc_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_protos_oricli_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_oricli_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_protos_oricli_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthCheckResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_protos_oricli_rpc_proto protoreflect.FileDescriptor

const file_protos_oricli_rpc_proto_rawDesc = "" +
	"\n" +
	"\x17protos/oricli_rpc.proto\x12\n" +
	"oricli.rpc\"\x11\n" +
	"\x0fManifestRequest\"\x80\x01\n" +
	"\x0eModuleMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"operations\x18\x05 \x03(\tR\n" +
	"operations\"H\n" +
	"\x10ManifestResponse\x124\n" +
	"\amodules\x18\x01 \x03(\v2\x1a.oricli.rpc.ModuleMetadataR\amodules\"\x89\x01\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\tR\n" +
	"paramsJson\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\"q\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12HealthCheckRequest\"R\n" +
	"\x13HealthCheckResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage2\xf6\x01\n" +
	"\rModuleService\x12H\n" +
	"\vGetManifest\x12\x1b.oricli.rpc.ManifestRequest\x1a\x1c.oricli.rpc.ManifestResponse\x12K\n" +
	"\x10ExecuteOperation\x12\x1a.oricli.rpc.ExecuteRequest\x1a\x1b.oricli.rpc.ExecuteResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.oricli.rpc.HealthCheckRequest\x1a\x1f.oricli.rpc.HealthCheckResponseB.Z,github.com/thynaptic/oricli-go/rpc;oriclirpcb\x06proto3"

var (
	file_protos_oricli_rpc_proto_rawDescOnce sync.Once
	file_protos_oricli_rpc_proto_rawDescData []byte
)

func file_protos_oricli_rpc_proto_rawDescGZIP() []byte {
	file_protos_oricli_rpc_proto_rawDescOnce.Do(func() {
		file_protos_oricli_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_oricli_rpc_proto_rawDesc), len(file_protos_oricli_rpc_proto_rawDesc)))
	})
	return file_protos_oricli_rpc_proto_rawDescData
}

var file_protos_oricli_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_oricli_rpc_proto_goTypes = []any{
	(*ManifestRequest)(nil),     // 0: oricli.rpc.ManifestRequest
	(*ModuleMetadata)(nil),      // 1: oricli.rpc.ModuleMetadata
	(*ManifestResponse)(nil),    // 2: oricli.rpc.ManifestResponse
	(*ExecuteRequest)(nil),      // 3: oricli.rpc.ExecuteRequest
	(*ExecuteResponse)(nil),     // 4: oricli.rpc.ExecuteResponse
	(*HealthCheckRequest)(nil),  // 5: oricli.rpc.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 6: oricli.rpc.HealthCheckResponse
}
var file_protos_oricli_rpc_proto_depIdxs = []int32{
	1, // 0: oricli.rpc.ManifestResponse.modules:type_name -> oricli.rpc.ModuleMetadata
	0, // 1: oricli.rpc.ModuleService.GetManifest:input_type -> oricli.rpc.ManifestRequest
	3, // 2: oricli.rpc.ModuleService.ExecuteOperation:input_type -> oricli.rpc.ExecuteRequest
	5, // 3: oricli.rpc.ModuleService.HealthCheck:input_type -> oricli.rpc.HealthCheckRequest
	2, // 4: oricli.rpc.ModuleService.GetManifest:output_type -> oricli.rpc.ManifestResponse
	4, // 5: oricli.rpc.ModuleService.ExecuteOperation:output_type -> oricli.rpc.ExecuteResponse
	6, // 6: oricli.rpc.ModuleService.HealthCheck:output_type -> oricli.rpc.HealthCheckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_oricli_rpc_proto_init() }
func file_protos_oricli_rpc_proto_init() {
	if File_protos_oricli_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_oricli_rpc_proto_rawDesc), len(file_protos_oricli_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_oricli_rpc_proto_goTypes,
		DependencyIndexes: file_protos_oricli_rpc_proto_depIdxs,
		MessageInfos:      file_protos_oricli_rpc_proto_msgTypes,
	}.Build()
	File_protos_oricli_rpc_proto = out.File
	file_protos_oricli_rpc_proto_goTypes = nil
	file_protos_oricli_rpc_proto_depIdxs = nil
}
