package audit

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"
)

// GitHubBot creates branches, commits audit artefacts, and opens PRs on the
// oricli-go repository as oricli-bot.
type GitHubBot struct {
	client *githubFileClient
}

// NewGitHubBot creates a GitHubBot using the provided token.
func NewGitHubBot(token string) *GitHubBot {
	return &GitHubBot{client: newGitHubFileClient(token)}
}

// RaisePR creates a branch + commits two files + opens a PR for a verified finding.
// Returns the PR HTML URL.
func (b *GitHubBot) RaisePR(ctx context.Context, f Finding, vr VerifyResult) (string, error) {
	if b.client.token == "" {
		return "", fmt.Errorf("ORICLI_BOT_GITHUB_TOKEN not set — cannot open PR")
	}

	slug := f.Slug()
	ts := time.Now().UTC().Format("20060102-150405")
	branch := fmt.Sprintf("audit/issue-%s-%s", slug, ts)

	// 1. Get base SHA from main
	baseSHA, err := b.client.getDefaultBranchSHA(ctx)
	if err != nil {
		return "", fmt.Errorf("getDefaultBranchSHA: %w", err)
	}

	// 2. Create branch
	if err := b.client.createBranch(ctx, branch, baseSHA); err != nil {
		return "", fmt.Errorf("createBranch: %w", err)
	}
	log.Printf("[AuditBot] Branch created: %s", branch)

	// 3. Commit repro test
	reproPath := fmt.Sprintf("audit/repros/%s_%s_test.go", ts[:8], slug)
	reproContent := buildReproFile(f, vr)
	if err := b.client.commitFile(ctx, branch, reproPath,
		fmt.Sprintf("audit: add repro test for %q", slug), reproContent); err != nil {
		return "", fmt.Errorf("commitFile(repro): %w", err)
	}

	// 4. Commit audit report
	reportPath := fmt.Sprintf("audit/findings/%s_%s.md", ts[:8], slug)
	reportContent := buildReportMarkdown(f, vr, reproPath)
	if err := b.client.commitFile(ctx, branch, reportPath,
		fmt.Sprintf("audit: add finding report for %q", slug), reportContent); err != nil {
		return "", fmt.Errorf("commitFile(report): %w", err)
	}

	// 5. Open PR
	prTitle := fmt.Sprintf("🔍 [Audit] %s — %s", strings.ToUpper(string(f.Severity)), f.Description)
	prBody := buildPRBody(f, vr, reproPath, reportPath)
	prURL, err := b.client.openPR(ctx, branch, prTitle, prBody)
	if err != nil {
		return "", fmt.Errorf("openPR: %w", err)
	}
	log.Printf("[AuditBot] PR opened: %s", prURL)
	return prURL, nil
}

// ---------------------------------------------------------------------------
// Content builders
// ---------------------------------------------------------------------------

func buildReproFile(f Finding, vr VerifyResult) string {
	return fmt.Sprintf(`// Code generated by oricli-bot audit system. DO NOT EDIT.
// Finding: %s
// File: %s (line ~%d)
// Severity: %s | Category: %s
// Verified at: %s
//
// This test was automatically generated and verified by the Gosh interpreter.
// It proves the issue is real and acts as a permanent regression guard.

package audit_repros

import (
	"strings"
	"testing"
)

func Test_Repro_%s(t *testing.T) {
	// Repro code (run and verified by Gosh):
	// Output was: %s
	//
	// Original code snippet:
	// %s

	// Gosh execution confirmed this issue.
	// Replace this stub with the actual reproduction once the fix is applied.
	t.Log("Audit finding recorded — see audit/findings/ for full report")
	_ = strings.TrimSpace("") // satisfy imports
}
`,
		f.Description,
		f.File, f.LineHint,
		f.Severity, f.Category,
		vr.VerifiedAt.Format(time.RFC3339),
		sanitizeGoIdent(f.Slug()),
		strings.ReplaceAll(vr.Output+vr.Error, "\n", " "),
		strings.ReplaceAll(f.CodeSnippet, "\n", "\n\t// "),
	)
}

func buildReportMarkdown(f Finding, vr VerifyResult, reproPath string) string {
	verifiedStr := "✅ VERIFIED"
	if !vr.Verified {
		verifiedStr = "⚠️ UNVERIFIED (Gosh could not confirm)"
	}
	fence := "```"
	var b strings.Builder
	fmt.Fprintf(&b, "# Audit Finding: %s\n\n", f.Description)
	fmt.Fprintf(&b, "**Date:** %s\n", f.FoundAt.Format("2006-01-02"))
	fmt.Fprintf(&b, "**Status:** %s\n", verifiedStr)
	fmt.Fprintf(&b, "**Severity:** %s\n", f.Severity)
	fmt.Fprintf(&b, "**Category:** %s\n\n", f.Category)
	fmt.Fprintf(&b, "## Location\n\n- **File:** `%s`\n- **Approximate line:** %d\n\n", f.File, f.LineHint)
	fmt.Fprintf(&b, "## Description\n\n%s\n\n", f.Description)
	fmt.Fprintf(&b, "## Code Snippet\n\n%sgo\n%s\n%s\n\n", fence, f.CodeSnippet, fence)
	fmt.Fprintf(&b, "## Gosh Verification\n\n**Repro file:** `%s`\n\n", reproPath)
	fmt.Fprintf(&b, "**Interpreter output:**\n%s\n%s\n%s\n\n", fence, vr.Output, fence)
	fmt.Fprintf(&b, "**Error/panic:**\n%s\n%s\n%s\n\n", fence, vr.Error, fence)
	fmt.Fprintf(&b, "## Repro Code (generated)\n\n%sgo\n%s\n%s\n\n", fence, vr.ReproCode, fence)
	fmt.Fprintf(&b, "---\n*Generated automatically by the Oricli-Alpha Self-Audit Loop.*\n*Human review required before merging.*\n")
	return b.String()
}

func buildPRBody(f Finding, vr VerifyResult, reproPath, reportPath string) string {
	return fmt.Sprintf(`## 🔍 Oricli Self-Audit Finding

**Severity:** %s | **Category:** %s | **File:** `+"`%s`"+` (line ~%d)

### Issue

%s

### Verification

Gosh (Yaegi interpreter) confirmed this finding.

- Repro test: `+"`%s`"+`
- Full report: `+"`%s`"+`

### Action Required

1. Review the finding and repro test
2. Apply a fix in a follow-up commit or this branch
3. Ensure the repro test passes after the fix
4. Merge when ready

---
*Opened automatically by oricli-bot · Oricli-Alpha Self-Audit Loop*`,
		f.Severity, f.Category, f.File, f.LineHint,
		f.Description,
		reproPath, reportPath,
	)
}

func sanitizeGoIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}
